# Generated by Django 4.0.5 on 2022-07-16 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacherLogin', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('year_of_study', models.IntegerField(null=True)),
                ('semester', models.IntegerField(null=True)),
                ('branch', models.CharField(max_length=50)),
                ('uni_id', models.CharField(max_length=11, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledClass',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolled_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherLogin.class')),
                ('enrolled_course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject', to_field='course_name')),
                ('enrolled_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentLogin.student', to_field='uni_id')),
            ],
        ),
    ]
