# Generated by Django 4.0.5 on 2022-07-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherLogin', '0001_initial'),
        ('studentLogin', '0002_remove_enrolledclass_enrolled_course_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledclass',
            unique_together={('enrolled_class_id', 'enrolled_student_id')},
        ),
    ]
