# Generated by Django 4.0.5 on 2022-07-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('pdf_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherLogin.class')),
            ],
        ),
    ]
